name: flutter_application_2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Check In.png
    - assets/GoCar.png
    - assets/GoFood.png
    - assets/GoMart.png
    - assets/GoPulsa.png
    - assets/GoRide.png
    - assets/GoSend.png
    - assets/banner.jpg
    - assets/upn.jpg
    - assets/vaccine.jpg
    - assets/results.jpg
    - assets/ehac.jpg
    - assets/travel.jpg
    - assets/telemedicine.jpg
    - assets/healthcare.jpg
    - assets/tangan.jpg
    - assets/scan.png
